name: .NET构建

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - '*'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: 设置.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.203
    - name: 更新依赖
      run: dotnet restore
    - name: 构建
      run: dotnet build
    - name: 更新构建文件
      uses: actions/upload-artifact@v2
      with:
        name: "McPing"
        path: build_out
